"""empty message

Revision ID: 1fec74ba9028
Revises: 09b2ce81125e
Create Date: 2024-04-29 18:26:02.633454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fec74ba9028'
down_revision: Union[str, None] = '09b2ce81125e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('like', sa.Integer(), nullable=False),
    sa.Column('dislike', sa.Integer(), nullable=False),
    sa.Column('watched', sa.Integer(), nullable=False),
    sa.Column('article_link', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_title',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cmmnts', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['title.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('title_id', 'user_id')
    )
    op.add_column('user', sa.Column('description', sa.String(), nullable=False))
    op.add_column('user', sa.Column('date_of_registration', sa.Date(), nullable=False))
    op.add_column('user', sa.Column('mail', sa.String(), nullable=False))
    op.add_column('user', sa.Column('psw', sa.String(), nullable=False))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'psw')
    op.drop_column('user', 'mail')
    op.drop_column('user', 'date_of_registration')
    op.drop_column('user', 'description')
    op.drop_table('user_title')
    op.drop_table('title')
    # ### end Alembic commands ###
